<?php

namespace CRGDaily;

class CraigslistCities{
	
	public $lastCity;
	
	public $listOfSitePrefixes = array("start", "auburn", "abilene", "akroncanton", "albany", "albanyga", "albuquerque", "allentown", "altoona", "amarillo", "ames", "anchorage", "annapolis", "annarbor", "appleton", "asheville", "ashtabula", "athensga", "athensohio", "atlanta", "augusta", "austin", "bakersfield", "baltimore", "batonrouge", "battlecreek", "beaumont", "bellingham", "bemidji", "bend", "bgky", "bham", "bigbend", "billings", "binghamton", "bismarck", "blacksburg", "bn", "boise", "boone", "boston", "boulder", "bozeman", "brainerd", "brownsville", "brunswick", "buffalo", "burlington", "butte", "capecod", "carbondale", "catskills", "cedarrapids", "cenla", "centralmich", "cfl", "chambana", "chambersburg", "charleston", "charlestonwv", "charlotte", "charlottesville", "chattanooga", "chautauqua", "chicago", "chico", "chillicothe", "cincinnati", "clarksville", "cleveland", "clovis", "cnj", "collegestation", "columbia", "columbiamo", "columbus", "columbusga", "cookeville", "corpuschristi", "corvallis", "cosprings", "csd", "dallas", "danville", "dayton", "daytona", "decatur", "delaware", "delrio", "denver", "desmoines", "detroit", "dothan", "dubuque", "duluth", "eastco", "easternshore", "eastidaho", "eastky", "eastnc", "eastoregon", "easttexas", "eauclaire", "elko", "elmira", "elpaso", "enid", "erie", "eugene", "fairbanks", "fargo", "farmington", "fayar", "fayetteville", "fingerlakes", "flagstaff", "flint", "florencesc", "fortcollins", "fortdodge", "fortmyers", "fortsmith", "frederick", "fredericksburg", "fresno", "gadsden", "gainesville", "galveston", "glensfalls", "goldcountry", "grandforks", "grandisland", "grandrapids", "greatfalls", "greenbay", "greensboro", "greenville", "gulfport", "hanford", "harrisburg", "harrisonburg", "hartford", "hattiesburg", "helena", "hickory", "hiltonhead", "holland", "honolulu", "houma", "houston", "hudsonvalley", "humboldt", "huntington", "huntsville", "imperial", "inlandempire", "iowacity", "ithaca", "jackson", "jacksontn", "jacksonville", "janesville", "jerseyshore", "jonesboro", "joplin", "juneau", "jxn", "kalamazoo", "kalispell", "kansascity", "kenai", "keys", "killeen", "kirksville", "klamath", "knoxville", "kpr", "ksu", "lacrosse", "lafayette", "lakecharles", "lakecity", "lakeland", "lancaster", "lansing", "laredo", "lasalle", "lascruces", "lasvegas", "lawrence", "lawton", "lewiston", "lexington", "limaohio", "lincoln", "littlerock", "logan", "longisland", "losangeles", "louisville", "loz", "lubbock", "lynchburg", "macon", "madison", "maine", "mankato", "mansfield", "marshall", "martinsburg", "masoncity", "mattoon", "mcallen", "meadville", "medford", "memphis", "mendocino", "merced", "meridian", "miami", "micronesia", "milwaukee", "minneapolis", "missoula", "mobile", "modesto", "mohave", "monroe", "monroemi", "montana", "monterey", "montgomery", "morgantown", "moseslake", "muskegon", "myrtlebeach", "nacogdoches", "nashville", "natchez", "nd", "nesd", "newhaven", "newjersey", "newlondon", "neworleans", "newyork", "nh", "nmi", "norfolk", "northernwi", "northmiss", "northplatte", "nwct", "nwga", "nwks", "ocala", "odessa", "ogden", "okaloosa", "oklahomacity", "olympic", "omaha", "oneonta", "onslow", "orangecounty", "oregoncoast", "orlando", "ottumwa", "outerbanks", "owensboro", "palmsprings", "panamacity", "parkersburg", "pennstate", "pensacola", "peoria", "philadelphia", "phoenix", "pittsburgh", "plattsburgh", "poconos", "porthuron", "portland", "potsdam", "prescott", "providence", "provo", "pueblo", "puertorico", "pullman", "quadcities", "quincy", "racine", "raleigh", "rapidcity", "reading", "redding", "reno", "richmond", "rmn", "roanoke", "rochester", "rockford", "rockies", "roseburg", "roswell", "sacramento", "saginaw", "salem", "salina", "saltlakecity", "sanangelo", "sanantonio", "sandiego", "sandusky", "sanmarcos", "santabarbara", "santafe", "santamaria", "sarasota", "savannah", "scottsbluff", "scranton", "sd", "seattle", "seks", "semo", "sfbay", "sheboygan", "shoals", "showlow", "shreveport", "sierravista", "siouxcity", "siouxfalls", "siskiyou", "skagit", "slo", "smd", "southbend", "southcoast", "southjersey", "spacecoast", "spokane", "springfield", "springfieldil", "statesboro", "staugustine", "stcloud", "stgeorge", "stillwater", "stjoseph", "stlouis", "stockton", "susanville", "swks", "swmi", "swv", "swva", "syracuse", "tallahassee", "tampa", "texarkana", "texoma", "thumb", "toledo", "topeka", "treasure", "tricities", "tucson", "tulsa", "tuscaloosa", "tuscarawas", "twinfalls", "twintiers", "up", "utica", "valdosta", "ventura", "victoriatx", "visalia", "waco", "washingtondc", "waterloo", "watertown", "wausau", "wenatchee", "westernmass", "westky", "westmd", "westslope", "wheeling", "wichita", "wichitafalls", "williamsport", "wilmington", "winchester", "winstonsalem", "worcester", "wv", "wyoming", "yakima", "york", "youngstown", "yubasutter", "yuma", "zanesville");
	
    public function __construct() {
        $this->populateArrayOfLinks();
    }
    
    public function checkForCityOptionAndSetIfEmpty(){
    	if (!get_option('crg-daily-city')) {
    		$firstItem = $first_value = reset($this->listOfSitePrefixes);
    		add_option('crg-daily-city', $firstItem);
    	}
    }
    
    public function returnCityArrayKey(){
    	$city = get_option('crg-daily-city');
    	$array = $this->listOfSitePrefixes;
    	$key = array_search($city, $array);
    	return $key;
    }
    
    public function setNumberOfCitiesOption(){
    	//sets the total number of cities:
    	$array = $this->listOfSitePrefixes;
    	$numberOfCities = count($array);
    	update_option('crg-total-number-of-cities', $numberOfCities);
    }
    
    public function fastForwardNextCity(){
    	$next = $this->getNextCityName();
    	
    	//A-B test:
    	update_option('crg-daily-city', $next);
    	//update_option('crg-daily-city', 'yuma');
    }
    
    public function getNextCityName() {
        $current = get_option('crg-daily-city');
        $sites = $this->listOfSitePrefixes;
        $nextkey = array_search($current, $sites) + 1;
        if ($nextkey == count($sites)) {
            // reached end of array, reset:
            $nextkey = 0;
        }
        $next = $sites[$nextkey];
        return $next;
    }

    public function isLastCity(){
    		$lastCity = array_pop($this->listOfSitePrefixes);
    		if (get_option('crg-daily-city') == $lastCity){return TRUE;}else{return FALSE;}
    }
    
    public function returnKeyOfCity($needle){
    	$listOfSitePrefixes = $this->listOfSitePrefixes;
		$x = 0;
		foreach ($listOfSitePrefixes as $haystack){
			if($needle == $haystack){
				return $x;
			}
			$x = $x + 1;
		}
		return false;
    } 
    
    public function returnTotalNumberOfCities(){
    	$array = $this->arrayOfLinks;
    	$numberOfCities= count($array);
    	return $numberOfCities;
    }
    
    public function getSiteStringByPointer($pointer){
        $arrayOfLinks = $this->arrayOfLinks;
        $link = $arrayOfLinks[$pointer];
        $URL = $this->getBetween('"', '"', $link);
        return $URL;
    }
    
    public function getBetween($var1="",$var2="",$pool){
        $temp1 = strpos($pool,$var1)+strlen($var1);
        $result = substr($pool,$temp1,strlen($pool));
        $dd=strpos($result,$var2);
        if($dd == 0){
            $dd = strlen($result);
        }
        
        return substr($result,0,$dd);
    }
    
    public function getNextCityObject(){
        $arrayOfLinks = $this->arrayOfLinks;
        //var_dump($arrayOfLinks);die();
        $maxPointer = count($arrayOfLinks);
        $TickerPointerForListOfSites = new TickerPointerForListOfSites($maxPointer);
        $pointer = $TickerPointerForListOfSites->pointer;
        $TickerPointerForListOfSites->advancePointer();
        $anchorLink = $arrayOfLinks[$pointer];
        //echo ("Pointer: $pointer AL: $anchorLink"); die();
        $CityObject = new CityObject($anchorLink);
        //var_dump($CityObject);die();
        return $CityObject;
    }
    
    public $arrayOfLinks = array();
    public function populateArrayOfLinks(){
        
        $arrayOfLinks = array();
        array_push($arrayOfLinks, '<a href="https://auburn.craigslist.org/">auburn</a>');
        array_push($arrayOfLinks, '<a href="https://bham.craigslist.org/">birmingham</a>');
        array_push($arrayOfLinks, '<a href="https://dothan.craigslist.org/">dothan</a>');
        array_push($arrayOfLinks, '<a href="https://shoals.craigslist.org/">florence / muscle shoals</a>');
        array_push($arrayOfLinks, '<a href="https://gadsden.craigslist.org/">gadsden-anniston</a>');
        array_push($arrayOfLinks, '<a href="https://huntsville.craigslist.org/">huntsville / decatur</a>');
        array_push($arrayOfLinks, '<a href="https://mobile.craigslist.org/">mobile</a>');
        array_push($arrayOfLinks, '<a href="https://montgomery.craigslist.org/">montgomery</a>');
        array_push($arrayOfLinks, '<a href="https://tuscaloosa.craigslist.org/">tuscaloosa</a>');
        array_push($arrayOfLinks, '<a href="https://anchorage.craigslist.org/">anchorage / mat-su</a>');
        array_push($arrayOfLinks, '<a href="https://fairbanks.craigslist.org/">fairbanks</a>');
        array_push($arrayOfLinks, '<a href="https://kenai.craigslist.org/">kenai peninsula</a>');
        array_push($arrayOfLinks, '<a href="https://juneau.craigslist.org/">southeast alaska</a>');
        array_push($arrayOfLinks, '<a href="https://flagstaff.craigslist.org/">flagstaff / sedona</a>');
        array_push($arrayOfLinks, '<a href="https://mohave.craigslist.org/">mohave county</a>');
        array_push($arrayOfLinks, '<a href="https://phoenix.craigslist.org/">phoenix</a>');
        array_push($arrayOfLinks, '<a href="https://prescott.craigslist.org/">prescott</a>');
        array_push($arrayOfLinks, '<a href="https://showlow.craigslist.org/">show low</a>');
        array_push($arrayOfLinks, '<a href="https://sierravista.craigslist.org/">sierra vista</a>');
        array_push($arrayOfLinks, '<a href="https://tucson.craigslist.org/">tucson</a>');
        array_push($arrayOfLinks, '<a href="https://yuma.craigslist.org/">yuma</a>');
        array_push($arrayOfLinks, '<a href="https://fayar.craigslist.org/">fayetteville </a>');
        array_push($arrayOfLinks, '<a href="https://fortsmith.craigslist.org/">fort smith</a>');
        array_push($arrayOfLinks, '<a href="https://jonesboro.craigslist.org/">jonesboro</a>');
        array_push($arrayOfLinks, '<a href="https://littlerock.craigslist.org/">little rock</a>');
        array_push($arrayOfLinks, '<a href="https://texarkana.craigslist.org/">texarkana</a>');
        array_push($arrayOfLinks, '<a href="https://bakersfield.craigslist.org/">bakersfield</a>');
        array_push($arrayOfLinks, '<a href="https://chico.craigslist.org/">chico</a>');
        array_push($arrayOfLinks, '<a href="https://fresno.craigslist.org/">fresno / madera</a>');
        array_push($arrayOfLinks, '<a href="https://goldcountry.craigslist.org/">gold country</a>');
        array_push($arrayOfLinks, '<a href="https://hanford.craigslist.org/">hanford-corcoran</a>');
        array_push($arrayOfLinks, '<a href="https://humboldt.craigslist.org/">humboldt county</a>');
        array_push($arrayOfLinks, '<a href="https://imperial.craigslist.org/">imperial county</a>');
        array_push($arrayOfLinks, '<a href="https://inlandempire.craigslist.org/">inland empire</a>');
        array_push($arrayOfLinks, '<a href="https://losangeles.craigslist.org/">los angeles</a>');
        array_push($arrayOfLinks, '<a href="https://mendocino.craigslist.org/">mendocino county</a>');
        array_push($arrayOfLinks, '<a href="https://merced.craigslist.org/">merced</a>');
        array_push($arrayOfLinks, '<a href="https://modesto.craigslist.org/">modesto</a>');
        array_push($arrayOfLinks, '<a href="https://monterey.craigslist.org/">monterey bay</a>');
        array_push($arrayOfLinks, '<a href="https://orangecounty.craigslist.org/">orange county</a>');
        array_push($arrayOfLinks, '<a href="https://palmsprings.craigslist.org/">palm springs</a>');
        array_push($arrayOfLinks, '<a href="https://redding.craigslist.org/">redding</a>');
        array_push($arrayOfLinks, '<a href="https://sacramento.craigslist.org/">sacramento</a>');
        array_push($arrayOfLinks, '<a href="https://sandiego.craigslist.org/">san diego</a>');
        array_push($arrayOfLinks, '<a href="https://sfbay.craigslist.org/">san francisco bay area</a>');
        array_push($arrayOfLinks, '<a href="https://slo.craigslist.org/">san luis obispo</a>');
        array_push($arrayOfLinks, '<a href="https://santabarbara.craigslist.org/">santa barbara</a>');
        array_push($arrayOfLinks, '<a href="https://santamaria.craigslist.org/">santa maria</a>');
        array_push($arrayOfLinks, '<a href="https://siskiyou.craigslist.org/">siskiyou county</a>');
        array_push($arrayOfLinks, '<a href="https://stockton.craigslist.org/">stockton</a>');
        array_push($arrayOfLinks, '<a href="https://susanville.craigslist.org/">susanville</a>');
        array_push($arrayOfLinks, '<a href="https://ventura.craigslist.org/">ventura county</a>');
        array_push($arrayOfLinks, '<a href="https://visalia.craigslist.org/">visalia-tulare</a>');
        array_push($arrayOfLinks, '<a href="https://yubasutter.craigslist.org/">yuba-sutter</a>');
        array_push($arrayOfLinks, '<a href="https://boulder.craigslist.org/">boulder</a>');
        array_push($arrayOfLinks, '<a href="https://cosprings.craigslist.org/">colorado springs</a>');
        array_push($arrayOfLinks, '<a href="https://denver.craigslist.org/">denver</a>');
        array_push($arrayOfLinks, '<a href="https://eastco.craigslist.org/">eastern CO</a>');
        array_push($arrayOfLinks, '<a href="https://fortcollins.craigslist.org/">fort collins / north CO</a>');
        array_push($arrayOfLinks, '<a href="https://rockies.craigslist.org/">high rockies</a>');
        array_push($arrayOfLinks, '<a href="https://pueblo.craigslist.org/">pueblo</a>');
        array_push($arrayOfLinks, '<a href="https://westslope.craigslist.org/">western slope</a>');
        array_push($arrayOfLinks, '<a href="https://newlondon.craigslist.org/">eastern CT</a>');
        array_push($arrayOfLinks, '<a href="https://hartford.craigslist.org/">hartford</a>');
        array_push($arrayOfLinks, '<a href="https://newhaven.craigslist.org/">new haven</a>');
        array_push($arrayOfLinks, '<a href="https://nwct.craigslist.org/">northwest CT</a>');
        array_push($arrayOfLinks, '<a href="https://delaware.craigslist.org/">delaware</a>');
        array_push($arrayOfLinks, '<a href="https://washingtondc.craigslist.org/">washington</a>');
        array_push($arrayOfLinks, '<a href="http://miami.craigslist.org/brw/">broward county</a>');
        array_push($arrayOfLinks, '<a href="https://daytona.craigslist.org/">daytona beach</a>');
        array_push($arrayOfLinks, '<a href="https://keys.craigslist.org/">florida keys</a>');
        array_push($arrayOfLinks, '<a href="https://fortlauderdale.craigslist.org/">fort lauderdale</a>');
        array_push($arrayOfLinks, '<a href="https://fortmyers.craigslist.org/">ft myers / SW florida</a>');
        array_push($arrayOfLinks, '<a href="https://gainesville.craigslist.org/">gainesville</a>');
        array_push($arrayOfLinks, '<a href="https://cfl.craigslist.org/">heartland florida</a>');
        array_push($arrayOfLinks, '<a href="https://jacksonville.craigslist.org/">jacksonville</a>');
        array_push($arrayOfLinks, '<a href="https://lakeland.craigslist.org/">lakeland</a>');
        array_push($arrayOfLinks, '<a href="http://miami.craigslist.org/mdc/">miami / dade</a>');
        array_push($arrayOfLinks, '<a href="https://lakecity.craigslist.org/">north central FL</a>');
        array_push($arrayOfLinks, '<a href="https://ocala.craigslist.org/">ocala</a>');
        array_push($arrayOfLinks, '<a href="https://okaloosa.craigslist.org/">okaloosa / walton</a>');
        array_push($arrayOfLinks, '<a href="https://orlando.craigslist.org/">orlando</a>');
        array_push($arrayOfLinks, '<a href="https://panamacity.craigslist.org/">panama city</a>');
        array_push($arrayOfLinks, '<a href="https://pensacola.craigslist.org/">pensacola</a>');
        array_push($arrayOfLinks, '<a href="https://sarasota.craigslist.org/">sarasota-bradenton</a>');
        array_push($arrayOfLinks, '<a href="https://miami.craigslist.org/">south florida</a>');
        array_push($arrayOfLinks, '<a href="https://spacecoast.craigslist.org/">space coast</a>');
        array_push($arrayOfLinks, '<a href="https://staugustine.craigslist.org/">st augustine</a>');
        array_push($arrayOfLinks, '<a href="https://tallahassee.craigslist.org/">tallahassee</a>');
        array_push($arrayOfLinks, '<a href="https://tampa.craigslist.org/">tampa bay area</a>');
        array_push($arrayOfLinks, '<a href="https://treasure.craigslist.org/">treasure coast</a>');
        array_push($arrayOfLinks, '<a href="http://miami.craigslist.org/pbc/">palm beach county</a>');
        array_push($arrayOfLinks, '<a href="https://albanyga.craigslist.org/">albany </a>');
        array_push($arrayOfLinks, '<a href="https://athensga.craigslist.org/">athens</a>');
        array_push($arrayOfLinks, '<a href="https://atlanta.craigslist.org/">atlanta</a>');
        array_push($arrayOfLinks, '<a href="https://augusta.craigslist.org/">augusta</a>');
        array_push($arrayOfLinks, '<a href="https://brunswick.craigslist.org/">brunswick</a>');
        array_push($arrayOfLinks, '<a href="https://columbusga.craigslist.org/">columbus </a>');
        array_push($arrayOfLinks, '<a href="https://macon.craigslist.org/">macon / warner robins</a>');
        array_push($arrayOfLinks, '<a href="https://nwga.craigslist.org/">northwest GA</a>');
        array_push($arrayOfLinks, '<a href="https://savannah.craigslist.org/">savannah / hinesville</a>');
        array_push($arrayOfLinks, '<a href="https://statesboro.craigslist.org/">statesboro</a>');
        array_push($arrayOfLinks, '<a href="https://valdosta.craigslist.org/">valdosta</a>');
        array_push($arrayOfLinks, '<a href="https://honolulu.craigslist.org/">hawaii</a>');
        array_push($arrayOfLinks, '<a href="https://boise.craigslist.org/">boise</a>');
        array_push($arrayOfLinks, '<a href="https://eastidaho.craigslist.org/">east idaho</a>');
        array_push($arrayOfLinks, '<a href="https://lewiston.craigslist.org/">lewiston / clarkston</a>');
        array_push($arrayOfLinks, '<a href="https://twinfalls.craigslist.org/">twin falls</a>');
        array_push($arrayOfLinks, '<a href="https://bn.craigslist.org/">bloomington-normal</a>');
        array_push($arrayOfLinks, '<a href="https://chambana.craigslist.org/">champaign urbana</a>');
        array_push($arrayOfLinks, '<a href="https://chicago.craigslist.org/">chicago</a>');
        array_push($arrayOfLinks, '<a href="https://decatur.craigslist.org/">decatur</a>');
        array_push($arrayOfLinks, '<a href="https://lasalle.craigslist.org/">la salle co</a>');
        array_push($arrayOfLinks, '<a href="https://mattoon.craigslist.org/">mattoon-charleston</a>');
        array_push($arrayOfLinks, '<a href="https://peoria.craigslist.org/">peoria</a>');
        array_push($arrayOfLinks, '<a href="https://rockford.craigslist.org/">rockford</a>');
        array_push($arrayOfLinks, '<a href="https://carbondale.craigslist.org/">southern illinois</a>');
        array_push($arrayOfLinks, '<a href="https://springfieldil.craigslist.org/">springfield </a>');
        array_push($arrayOfLinks, '<a href="https://quincy.craigslist.org/">western IL</a>');
        array_push($arrayOfLinks, '<a href="https://bloomington.craigslist.org/">bloomington</a>');
        array_push($arrayOfLinks, '<a href="https://evansville.craigslist.org/">evansville</a>');
        array_push($arrayOfLinks, '<a href="https://fortwayne.craigslist.org/">fort wayne</a>');
        array_push($arrayOfLinks, '<a href="https://indianapolis.craigslist.org/">indianapolis</a>');
        array_push($arrayOfLinks, '<a href="https://kokomo.craigslist.org/">kokomo</a>');
        array_push($arrayOfLinks, '<a href="https://tippecanoe.craigslist.org/">lafayette / west lafayette</a>');
        array_push($arrayOfLinks, '<a href="https://muncie.craigslist.org/">muncie / anderson</a>');
        array_push($arrayOfLinks, '<a href="https://richmondin.craigslist.org/">richmond </a>');
        array_push($arrayOfLinks, '<a href="https://southbend.craigslist.org/">south bend / michiana</a>');
        array_push($arrayOfLinks, '<a href="https://terrehaute.craigslist.org/">terre haute</a>');
        array_push($arrayOfLinks, '<a href="https://ames.craigslist.org/">ames</a>');
        array_push($arrayOfLinks, '<a href="https://cedarrapids.craigslist.org/">cedar rapids</a>');
        array_push($arrayOfLinks, '<a href="https://desmoines.craigslist.org/">des moines</a>');
        array_push($arrayOfLinks, '<a href="https://dubuque.craigslist.org/">dubuque</a>');
        array_push($arrayOfLinks, '<a href="https://fortdodge.craigslist.org/">fort dodge</a>');
        array_push($arrayOfLinks, '<a href="https://iowacity.craigslist.org/">iowa city</a>');
        array_push($arrayOfLinks, '<a href="https://masoncity.craigslist.org/">mason city</a>');
        array_push($arrayOfLinks, '<a href="https://quadcities.craigslist.org/">quad cities</a>');
        array_push($arrayOfLinks, '<a href="https://siouxcity.craigslist.org/">sioux city</a>');
        array_push($arrayOfLinks, '<a href="https://ottumwa.craigslist.org/">southeast IA</a>');
        array_push($arrayOfLinks, '<a href="https://waterloo.craigslist.org/">waterloo / cedar falls</a>');
        array_push($arrayOfLinks, '<a href="https://lawrence.craigslist.org/">lawrence</a>');
        array_push($arrayOfLinks, '<a href="https://ksu.craigslist.org/">manhattan</a>');
        array_push($arrayOfLinks, '<a href="https://nwks.craigslist.org/">northwest KS</a>');
        array_push($arrayOfLinks, '<a href="https://salina.craigslist.org/">salina</a>');
        array_push($arrayOfLinks, '<a href="https://seks.craigslist.org/">southeast KS</a>');
        array_push($arrayOfLinks, '<a href="https://swks.craigslist.org/">southwest KS</a>');
        array_push($arrayOfLinks, '<a href="https://topeka.craigslist.org/">topeka</a>');
        array_push($arrayOfLinks, '<a href="https://wichita.craigslist.org/">wichita</a>');
        array_push($arrayOfLinks, '<a href="https://bgky.craigslist.org/">bowling green</a>');
        array_push($arrayOfLinks, '<a href="https://eastky.craigslist.org/">eastern kentucky</a>');
        array_push($arrayOfLinks, '<a href="https://lexington.craigslist.org/">lexington</a>');
        array_push($arrayOfLinks, '<a href="https://louisville.craigslist.org/">louisville</a>');
        array_push($arrayOfLinks, '<a href="https://owensboro.craigslist.org/">owensboro</a>');
        array_push($arrayOfLinks, '<a href="https://westky.craigslist.org/">western KY</a>');
        array_push($arrayOfLinks, '<a href="https://batonrouge.craigslist.org/">baton rouge</a>');
        array_push($arrayOfLinks, '<a href="https://cenla.craigslist.org/">central louisiana</a>');
        array_push($arrayOfLinks, '<a href="https://houma.craigslist.org/">houma</a>');
        array_push($arrayOfLinks, '<a href="https://lafayette.craigslist.org/">lafayette</a>');
        array_push($arrayOfLinks, '<a href="https://lakecharles.craigslist.org/">lake charles</a>');
        array_push($arrayOfLinks, '<a href="https://monroe.craigslist.org/">monroe</a>');
        array_push($arrayOfLinks, '<a href="https://neworleans.craigslist.org/">new orleans</a>');
        array_push($arrayOfLinks, '<a href="https://shreveport.craigslist.org/">shreveport</a>');
        array_push($arrayOfLinks, '<a href="https://maine.craigslist.org/">maine</a>');
        array_push($arrayOfLinks, '<a href="https://annapolis.craigslist.org/">annapolis</a>');
        array_push($arrayOfLinks, '<a href="https://baltimore.craigslist.org/">baltimore</a>');
        array_push($arrayOfLinks, '<a href="https://easternshore.craigslist.org/">eastern shore</a>');
        array_push($arrayOfLinks, '<a href="https://frederick.craigslist.org/">frederick</a>');
        array_push($arrayOfLinks, '<a href="https://smd.craigslist.org/">southern maryland</a>');
        array_push($arrayOfLinks, '<a href="https://westmd.craigslist.org/">western maryland</a>');
        array_push($arrayOfLinks, '<a href="https://boston.craigslist.org/">boston</a>');
        array_push($arrayOfLinks, '<a href="https://capecod.craigslist.org/">cape cod / islands</a>');
        array_push($arrayOfLinks, '<a href="https://southcoast.craigslist.org/">south coast</a>');
        array_push($arrayOfLinks, '<a href="https://westernmass.craigslist.org/">western massachusetts</a>');
        array_push($arrayOfLinks, '<a href="https://worcester.craigslist.org/">worcester / central MA</a>');
        array_push($arrayOfLinks, '<a href="https://annarbor.craigslist.org/">ann arbor</a>');
        array_push($arrayOfLinks, '<a href="https://battlecreek.craigslist.org/">battle creek</a>');
        array_push($arrayOfLinks, '<a href="https://centralmich.craigslist.org/">central michigan</a>');
        array_push($arrayOfLinks, '<a href="https://detroit.craigslist.org/">detroit metro</a>');
        array_push($arrayOfLinks, '<a href="https://flint.craigslist.org/">flint</a>');
        array_push($arrayOfLinks, '<a href="https://grandrapids.craigslist.org/">grand rapids</a>');
        array_push($arrayOfLinks, '<a href="https://holland.craigslist.org/">holland</a>');
        array_push($arrayOfLinks, '<a href="https://jxn.craigslist.org/">jackson </a>');
        array_push($arrayOfLinks, '<a href="https://kalamazoo.craigslist.org/">kalamazoo</a>');
        array_push($arrayOfLinks, '<a href="https://lansing.craigslist.org/">lansing</a>');
        array_push($arrayOfLinks, '<a href="https://monroemi.craigslist.org/">monroe </a>');
        array_push($arrayOfLinks, '<a href="https://muskegon.craigslist.org/">muskegon</a>');
        array_push($arrayOfLinks, '<a href="https://nmi.craigslist.org/">northern michigan</a>');
        array_push($arrayOfLinks, '<a href="https://porthuron.craigslist.org/">port huron</a>');
        array_push($arrayOfLinks, '<a href="https://saginaw.craigslist.org/">saginaw-midland-baycity</a>');
        array_push($arrayOfLinks, '<a href="https://swmi.craigslist.org/">southwest michigan</a>');
        array_push($arrayOfLinks, '<a href="https://thumb.craigslist.org/">the thumb</a>');
        array_push($arrayOfLinks, '<a href="https://up.craigslist.org/">upper peninsula</a>');
        array_push($arrayOfLinks, '<a href="https://bemidji.craigslist.org/">bemidji</a>');
        array_push($arrayOfLinks, '<a href="https://brainerd.craigslist.org/">brainerd</a>');
        array_push($arrayOfLinks, '<a href="https://duluth.craigslist.org/">duluth / superior</a>');
        array_push($arrayOfLinks, '<a href="https://mankato.craigslist.org/">mankato</a>');
        array_push($arrayOfLinks, '<a href="https://minneapolis.craigslist.org/">minneapolis / st paul</a>');
        array_push($arrayOfLinks, '<a href="https://rmn.craigslist.org/">rochester </a>');
        array_push($arrayOfLinks, '<a href="https://marshall.craigslist.org/">southwest MN</a>');
        array_push($arrayOfLinks, '<a href="https://stcloud.craigslist.org/">st cloud</a>');
        array_push($arrayOfLinks, '<a href="https://gulfport.craigslist.org/">gulfport / biloxi</a>');
        array_push($arrayOfLinks, '<a href="https://hattiesburg.craigslist.org/">hattiesburg</a>');
        array_push($arrayOfLinks, '<a href="https://jackson.craigslist.org/">jackson</a>');
        array_push($arrayOfLinks, '<a href="https://meridian.craigslist.org/">meridian</a>');
        array_push($arrayOfLinks, '<a href="https://northmiss.craigslist.org/">north mississippi</a>');
        array_push($arrayOfLinks, '<a href="https://natchez.craigslist.org/">southwest MS</a>');
        array_push($arrayOfLinks, '<a href="https://columbiamo.craigslist.org/">columbia / jeff city</a>');
        array_push($arrayOfLinks, '<a href="https://joplin.craigslist.org/">joplin</a>');
        array_push($arrayOfLinks, '<a href="https://kansascity.craigslist.org/">kansas city</a>');
        array_push($arrayOfLinks, '<a href="https://kirksville.craigslist.org/">kirksville</a>');
        array_push($arrayOfLinks, '<a href="https://loz.craigslist.org/">lake of the ozarks</a>');
        array_push($arrayOfLinks, '<a href="https://semo.craigslist.org/">southeast missouri</a>');
        array_push($arrayOfLinks, '<a href="https://springfield.craigslist.org/">springfield</a>');
        array_push($arrayOfLinks, '<a href="https://stjoseph.craigslist.org/">st joseph</a>');
        array_push($arrayOfLinks, '<a href="https://stlouis.craigslist.org/">st louis</a>');
        array_push($arrayOfLinks, '<a href="https://billings.craigslist.org/">billings</a>');
        array_push($arrayOfLinks, '<a href="https://bozeman.craigslist.org/">bozeman</a>');
        array_push($arrayOfLinks, '<a href="https://butte.craigslist.org/">butte</a>');
        array_push($arrayOfLinks, '<a href="https://greatfalls.craigslist.org/">great falls</a>');
        array_push($arrayOfLinks, '<a href="https://helena.craigslist.org/">helena</a>');
        array_push($arrayOfLinks, '<a href="https://kalispell.craigslist.org/">kalispell</a>');
        array_push($arrayOfLinks, '<a href="https://missoula.craigslist.org/">missoula</a>');
        array_push($arrayOfLinks, '<a href="https://montana.craigslist.org/">eastern montana</a>');
        array_push($arrayOfLinks, '<a href="https://grandisland.craigslist.org/">grand island</a>');
        array_push($arrayOfLinks, '<a href="https://lincoln.craigslist.org/">lincoln</a>');
        array_push($arrayOfLinks, '<a href="https://northplatte.craigslist.org/">north platte</a>');
        array_push($arrayOfLinks, '<a href="https://omaha.craigslist.org/">omaha / council bluffs</a>');
        array_push($arrayOfLinks, '<a href="https://elko.craigslist.org/">elko</a>');
        array_push($arrayOfLinks, '<a href="https://lasvegas.craigslist.org/">las vegas</a>');
        array_push($arrayOfLinks, '<a href="https://reno.craigslist.org/">reno / tahoe</a>');
        array_push($arrayOfLinks, '<a href="https://nh.craigslist.org/">new hampshire</a>');
        array_push($arrayOfLinks, '<a href="https://cnj.craigslist.org/">central NJ</a>');
        array_push($arrayOfLinks, '<a href="https://jerseyshore.craigslist.org/">jersey shore</a>');
        array_push($arrayOfLinks, '<a href="https://newjersey.craigslist.org/">north jersey</a>');
        array_push($arrayOfLinks, '<a href="https://southjersey.craigslist.org/">south jersey</a>');
        array_push($arrayOfLinks, '<a href="https://albuquerque.craigslist.org/">albuquerque</a>');
        array_push($arrayOfLinks, '<a href="https://clovis.craigslist.org/">clovis / portales</a>');
        array_push($arrayOfLinks, '<a href="https://farmington.craigslist.org/">farmington</a>');
        array_push($arrayOfLinks, '<a href="https://lascruces.craigslist.org/">las cruces</a>');
        array_push($arrayOfLinks, '<a href="https://roswell.craigslist.org/">roswell / carlsbad</a>');
        array_push($arrayOfLinks, '<a href="https://santafe.craigslist.org/">santa fe / taos</a>');
        array_push($arrayOfLinks, '<a href="https://albany.craigslist.org/">albany</a>');
        array_push($arrayOfLinks, '<a href="https://binghamton.craigslist.org/">binghamton</a>');
        array_push($arrayOfLinks, '<a href="https://buffalo.craigslist.org/">buffalo</a>');
        array_push($arrayOfLinks, '<a href="https://catskills.craigslist.org/">catskills</a>');
        array_push($arrayOfLinks, '<a href="https://chautauqua.craigslist.org/">chautauqua</a>');
        array_push($arrayOfLinks, '<a href="https://elmira.craigslist.org/">elmira-corning</a>');
        array_push($arrayOfLinks, '<a href="https://fingerlakes.craigslist.org/">finger lakes</a>');
        array_push($arrayOfLinks, '<a href="https://glensfalls.craigslist.org/">glens falls</a>');
        array_push($arrayOfLinks, '<a href="https://hudsonvalley.craigslist.org/">hudson valley</a>');
        array_push($arrayOfLinks, '<a href="https://ithaca.craigslist.org/">ithaca</a>');
        array_push($arrayOfLinks, '<a href="https://longisland.craigslist.org/">long island</a>');
        array_push($arrayOfLinks, '<a href="https://newyork.craigslist.org/">new york city</a>');
        array_push($arrayOfLinks, '<a href="https://oneonta.craigslist.org/">oneonta</a>');
        array_push($arrayOfLinks, '<a href="https://plattsburgh.craigslist.org/">plattsburgh-adirondacks</a>');
        array_push($arrayOfLinks, '<a href="https://potsdam.craigslist.org/">potsdam-canton-massena</a>');
        array_push($arrayOfLinks, '<a href="https://rochester.craigslist.org/">rochester</a>');
        array_push($arrayOfLinks, '<a href="https://syracuse.craigslist.org/">syracuse</a>');
        array_push($arrayOfLinks, '<a href="https://twintiers.craigslist.org/">twin tiers NY/PA</a>');
        array_push($arrayOfLinks, '<a href="https://utica.craigslist.org/">utica-rome-oneida</a>');
        array_push($arrayOfLinks, '<a href="https://watertown.craigslist.org/">watertown</a>');
        array_push($arrayOfLinks, '<a href="https://asheville.craigslist.org/">asheville</a>');
        array_push($arrayOfLinks, '<a href="https://boone.craigslist.org/">boone</a>');
        array_push($arrayOfLinks, '<a href="https://charlotte.craigslist.org/">charlotte</a>');
        array_push($arrayOfLinks, '<a href="https://eastnc.craigslist.org/">eastern NC</a>');
        array_push($arrayOfLinks, '<a href="https://fayetteville.craigslist.org/">fayetteville</a>');
        array_push($arrayOfLinks, '<a href="https://greensboro.craigslist.org/">greensboro</a>');
        array_push($arrayOfLinks, '<a href="https://hickory.craigslist.org/">hickory / lenoir</a>');
        array_push($arrayOfLinks, '<a href="https://onslow.craigslist.org/">jacksonville </a>');
        array_push($arrayOfLinks, '<a href="https://outerbanks.craigslist.org/">outer banks</a>');
        array_push($arrayOfLinks, '<a href="https://raleigh.craigslist.org/">raleigh / durham / CH</a>');
        array_push($arrayOfLinks, '<a href="https://wilmington.craigslist.org/">wilmington</a>');
        array_push($arrayOfLinks, '<a href="https://winstonsalem.craigslist.org/">winston-salem</a>');
        array_push($arrayOfLinks, '<a href="https://bismarck.craigslist.org/">bismarck</a>');
        array_push($arrayOfLinks, '<a href="https://fargo.craigslist.org/">fargo / moorhead</a>');
        array_push($arrayOfLinks, '<a href="https://grandforks.craigslist.org/">grand forks</a>');
        array_push($arrayOfLinks, '<a href="https://nd.craigslist.org/">north dakota</a>');
        array_push($arrayOfLinks, '<a href="https://akroncanton.craigslist.org/">akron / canton</a>');
        array_push($arrayOfLinks, '<a href="https://ashtabula.craigslist.org/">ashtabula</a>');
        array_push($arrayOfLinks, '<a href="https://athensohio.craigslist.org/">athens </a>');
        array_push($arrayOfLinks, '<a href="https://chillicothe.craigslist.org/">chillicothe</a>');
        array_push($arrayOfLinks, '<a href="https://cincinnati.craigslist.org/">cincinnati</a>');
        array_push($arrayOfLinks, '<a href="https://cleveland.craigslist.org/">cleveland</a>');
        array_push($arrayOfLinks, '<a href="https://columbus.craigslist.org/">columbus</a>');
        array_push($arrayOfLinks, '<a href="https://dayton.craigslist.org/">dayton / springfield</a>');
        array_push($arrayOfLinks, '<a href="https://limaohio.craigslist.org/">lima / findlay</a>');
        array_push($arrayOfLinks, '<a href="https://mansfield.craigslist.org/">mansfield</a>');
        array_push($arrayOfLinks, '<a href="https://sandusky.craigslist.org/">sandusky</a>');
        array_push($arrayOfLinks, '<a href="https://toledo.craigslist.org/">toledo</a>');
        array_push($arrayOfLinks, '<a href="https://tuscarawas.craigslist.org/">tuscarawas co</a>');
        array_push($arrayOfLinks, '<a href="https://youngstown.craigslist.org/">youngstown</a>');
        array_push($arrayOfLinks, '<a href="https://zanesville.craigslist.org/">zanesville / cambridge</a>');
        array_push($arrayOfLinks, '<a href="https://lawton.craigslist.org/">lawton</a>');
        array_push($arrayOfLinks, '<a href="https://enid.craigslist.org/">northwest OK</a>');
        array_push($arrayOfLinks, '<a href="https://oklahomacity.craigslist.org/">oklahoma city</a>');
        array_push($arrayOfLinks, '<a href="https://stillwater.craigslist.org/">stillwater</a>');
        array_push($arrayOfLinks, '<a href="https://tulsa.craigslist.org/">tulsa</a>');
        array_push($arrayOfLinks, '<a href="https://bend.craigslist.org/">bend</a>');
        array_push($arrayOfLinks, '<a href="https://corvallis.craigslist.org/">corvallis/albany</a>');
        array_push($arrayOfLinks, '<a href="https://eastoregon.craigslist.org/">east oregon</a>');
        array_push($arrayOfLinks, '<a href="https://eugene.craigslist.org/">eugene</a>');
        array_push($arrayOfLinks, '<a href="https://klamath.craigslist.org/">klamath falls</a>');
        array_push($arrayOfLinks, '<a href="https://medford.craigslist.org/">medford-ashland</a>');
        array_push($arrayOfLinks, '<a href="https://oregoncoast.craigslist.org/">oregon coast</a>');
        array_push($arrayOfLinks, '<a href="https://portland.craigslist.org/">portland</a>');
        array_push($arrayOfLinks, '<a href="https://roseburg.craigslist.org/">roseburg</a>');
        array_push($arrayOfLinks, '<a href="https://salem.craigslist.org/">salem</a>');
        array_push($arrayOfLinks, '<a href="https://altoona.craigslist.org/">altoona-johnstown</a>');
        array_push($arrayOfLinks, '<a href="https://chambersburg.craigslist.org/">cumberland valley</a>');
        array_push($arrayOfLinks, '<a href="https://erie.craigslist.org/">erie</a>');
        array_push($arrayOfLinks, '<a href="https://harrisburg.craigslist.org/">harrisburg</a>');
        array_push($arrayOfLinks, '<a href="https://lancaster.craigslist.org/">lancaster</a>');
        array_push($arrayOfLinks, '<a href="https://allentown.craigslist.org/">lehigh valley</a>');
        array_push($arrayOfLinks, '<a href="https://meadville.craigslist.org/">meadville</a>');
        array_push($arrayOfLinks, '<a href="https://philadelphia.craigslist.org/">philadelphia</a>');
        array_push($arrayOfLinks, '<a href="https://pittsburgh.craigslist.org/">pittsburgh</a>');
        array_push($arrayOfLinks, '<a href="https://poconos.craigslist.org/">poconos</a>');
        array_push($arrayOfLinks, '<a href="https://reading.craigslist.org/">reading</a>');
        array_push($arrayOfLinks, '<a href="https://scranton.craigslist.org/">scranton / wilkes-barre</a>');
        array_push($arrayOfLinks, '<a href="https://pennstate.craigslist.org/">state college</a>');
        array_push($arrayOfLinks, '<a href="https://williamsport.craigslist.org/">williamsport</a>');
        array_push($arrayOfLinks, '<a href="https://york.craigslist.org/">york</a>');
        array_push($arrayOfLinks, '<a href="https://providence.craigslist.org/">rhode island</a>');
        array_push($arrayOfLinks, '<a href="https://charleston.craigslist.org/">charleston</a>');
        array_push($arrayOfLinks, '<a href="https://columbia.craigslist.org/">columbia</a>');
        array_push($arrayOfLinks, '<a href="https://florencesc.craigslist.org/">florence</a>');
        array_push($arrayOfLinks, '<a href="https://greenville.craigslist.org/">greenville / upstate</a>');
        array_push($arrayOfLinks, '<a href="https://hiltonhead.craigslist.org/">hilton head</a>');
        array_push($arrayOfLinks, '<a href="https://myrtlebeach.craigslist.org/">myrtle beach</a>');
        array_push($arrayOfLinks, '<a href="https://nesd.craigslist.org/">northeast SD</a>');
        array_push($arrayOfLinks, '<a href="https://csd.craigslist.org/">pierre / central SD</a>');
        array_push($arrayOfLinks, '<a href="https://rapidcity.craigslist.org/">rapid city / west SD</a>');
        array_push($arrayOfLinks, '<a href="https://siouxfalls.craigslist.org/">sioux falls / SE SD</a>');
        array_push($arrayOfLinks, '<a href="https://sd.craigslist.org/">south dakota</a>');
        array_push($arrayOfLinks, '<a href="https://chattanooga.craigslist.org/">chattanooga</a>');
        array_push($arrayOfLinks, '<a href="https://clarksville.craigslist.org/">clarksville</a>');
        array_push($arrayOfLinks, '<a href="https://cookeville.craigslist.org/">cookeville</a>');
        array_push($arrayOfLinks, '<a href="https://jacksontn.craigslist.org/">jackson  </a>');
        array_push($arrayOfLinks, '<a href="https://knoxville.craigslist.org/">knoxville</a>');
        array_push($arrayOfLinks, '<a href="https://memphis.craigslist.org/">memphis</a>');
        array_push($arrayOfLinks, '<a href="https://nashville.craigslist.org/">nashville</a>');
        array_push($arrayOfLinks, '<a href="https://tricities.craigslist.org/">tri-cities</a>');
        array_push($arrayOfLinks, '<a href="https://abilene.craigslist.org/">abilene</a>');
        array_push($arrayOfLinks, '<a href="https://amarillo.craigslist.org/">amarillo</a>');
        array_push($arrayOfLinks, '<a href="https://austin.craigslist.org/">austin</a>');
        array_push($arrayOfLinks, '<a href="https://beaumont.craigslist.org/">beaumont / port arthur</a>');
        array_push($arrayOfLinks, '<a href="https://brownsville.craigslist.org/">brownsville</a>');
        array_push($arrayOfLinks, '<a href="https://collegestation.craigslist.org/">college station</a>');
        array_push($arrayOfLinks, '<a href="https://corpuschristi.craigslist.org/">corpus christi</a>');
        array_push($arrayOfLinks, '<a href="https://dallas.craigslist.org/">dallas / fort worth</a>');
        array_push($arrayOfLinks, '<a href="https://nacogdoches.craigslist.org/">deep east texas</a>');
        array_push($arrayOfLinks, '<a href="https://delrio.craigslist.org/">del rio / eagle pass</a>');
        array_push($arrayOfLinks, '<a href="https://elpaso.craigslist.org/">el paso</a>');
        array_push($arrayOfLinks, '<a href="https://galveston.craigslist.org/">galveston</a>');
        array_push($arrayOfLinks, '<a href="https://houston.craigslist.org/">houston</a>');
        array_push($arrayOfLinks, '<a href="https://killeen.craigslist.org/">killeen / temple / ft hood</a>');
        array_push($arrayOfLinks, '<a href="https://laredo.craigslist.org/">laredo</a>');
        array_push($arrayOfLinks, '<a href="https://lubbock.craigslist.org/">lubbock</a>');
        array_push($arrayOfLinks, '<a href="https://mcallen.craigslist.org/">mcallen / edinburg</a>');
        array_push($arrayOfLinks, '<a href="https://odessa.craigslist.org/">odessa / midland</a>');
        array_push($arrayOfLinks, '<a href="https://sanangelo.craigslist.org/">san angelo</a>');
        array_push($arrayOfLinks, '<a href="https://sanantonio.craigslist.org/">san antonio</a>');
        array_push($arrayOfLinks, '<a href="https://sanmarcos.craigslist.org/">san marcos</a>');
        array_push($arrayOfLinks, '<a href="https://bigbend.craigslist.org/">southwest TX</a>');
        array_push($arrayOfLinks, '<a href="https://texoma.craigslist.org/">texoma</a>');
        array_push($arrayOfLinks, '<a href="https://easttexas.craigslist.org/">tyler / east TX</a>');
        array_push($arrayOfLinks, '<a href="https://victoriatx.craigslist.org/">victoria </a>');
        array_push($arrayOfLinks, '<a href="https://waco.craigslist.org/">waco</a>');
        array_push($arrayOfLinks, '<a href="https://wichitafalls.craigslist.org/">wichita falls</a>');
        array_push($arrayOfLinks, '<a href="https://logan.craigslist.org/">logan</a>');
        array_push($arrayOfLinks, '<a href="https://ogden.craigslist.org/">ogden-clearfield</a>');
        array_push($arrayOfLinks, '<a href="https://provo.craigslist.org/">provo / orem</a>');
        array_push($arrayOfLinks, '<a href="https://saltlakecity.craigslist.org/">salt lake city</a>');
        array_push($arrayOfLinks, '<a href="https://stgeorge.craigslist.org/">st george</a>');
        array_push($arrayOfLinks, '<a href="https://vermont.craigslist.org/">vermont</a>');
        array_push($arrayOfLinks, '<a href="https://charlottesville.craigslist.org/">charlottesville</a>');
        array_push($arrayOfLinks, '<a href="https://danville.craigslist.org/">danville</a>');
        array_push($arrayOfLinks, '<a href="https://fredericksburg.craigslist.org/">fredericksburg</a>');
        array_push($arrayOfLinks, '<a href="https://norfolk.craigslist.org/">hampton roads</a>');
        array_push($arrayOfLinks, '<a href="https://harrisonburg.craigslist.org/">harrisonburg</a>');
        array_push($arrayOfLinks, '<a href="https://lynchburg.craigslist.org/">lynchburg</a>');
        array_push($arrayOfLinks, '<a href="https://blacksburg.craigslist.org/">new river valley</a>');
        array_push($arrayOfLinks, '<a href="https://richmond.craigslist.org/">richmond</a>');
        array_push($arrayOfLinks, '<a href="https://roanoke.craigslist.org/">roanoke</a>');
        array_push($arrayOfLinks, '<a href="https://swva.craigslist.org/">southwest VA</a>');
        array_push($arrayOfLinks, '<a href="https://winchester.craigslist.org/">winchester</a>');
        array_push($arrayOfLinks, '<a href="https://bellingham.craigslist.org/">bellingham</a>');
        array_push($arrayOfLinks, '<a href="https://kpr.craigslist.org/">kennewick-pasco-richland</a>');
        array_push($arrayOfLinks, '<a href="https://moseslake.craigslist.org/">moses lake</a>');
        array_push($arrayOfLinks, '<a href="https://olympic.craigslist.org/">olympic peninsula</a>');
        array_push($arrayOfLinks, '<a href="https://pullman.craigslist.org/">pullman / moscow</a>');
        array_push($arrayOfLinks, '<a href="https://seattle.craigslist.org/">seattle-tacoma</a>');
        array_push($arrayOfLinks, '<a href="https://skagit.craigslist.org/">skagit / island / SJI</a>');
        array_push($arrayOfLinks, '<a href="https://spokane.craigslist.org/">spokane / coeur d\'alene</a>');
        array_push($arrayOfLinks, '<a href="https://wenatchee.craigslist.org/">wenatchee</a>');
        array_push($arrayOfLinks, '<a href="https://yakima.craigslist.org/">yakima</a>');
        array_push($arrayOfLinks, '<a href="https://charlestonwv.craigslist.org/">charleston </a>');
        array_push($arrayOfLinks, '<a href="https://martinsburg.craigslist.org/">eastern panhandle</a>');
        array_push($arrayOfLinks, '<a href="https://huntington.craigslist.org/">huntington-ashland</a>');
        array_push($arrayOfLinks, '<a href="https://morgantown.craigslist.org/">morgantown</a>');
        array_push($arrayOfLinks, '<a href="https://wheeling.craigslist.org/">northern panhandle</a>');
        array_push($arrayOfLinks, '<a href="https://parkersburg.craigslist.org/">parkersburg-marietta</a>');
        array_push($arrayOfLinks, '<a href="https://swv.craigslist.org/">southern WV</a>');
        array_push($arrayOfLinks, '<a href="https://wv.craigslist.org/">west virginia (old)</a>');
        array_push($arrayOfLinks, '<a href="https://appleton.craigslist.org/">appleton-oshkosh-FDL</a>');
        array_push($arrayOfLinks, '<a href="https://eauclaire.craigslist.org/">eau claire</a>');
        array_push($arrayOfLinks, '<a href="https://greenbay.craigslist.org/">green bay</a>');
        array_push($arrayOfLinks, '<a href="https://janesville.craigslist.org/">janesville</a>');
        array_push($arrayOfLinks, '<a href="https://racine.craigslist.org/">kenosha-racine</a>');
        array_push($arrayOfLinks, '<a href="https://lacrosse.craigslist.org/">la crosse</a>');
        array_push($arrayOfLinks, '<a href="https://madison.craigslist.org/">madison</a>');
        array_push($arrayOfLinks, '<a href="https://milwaukee.craigslist.org/">milwaukee</a>');
        array_push($arrayOfLinks, '<a href="https://northernwi.craigslist.org/">northern WI</a>');
        array_push($arrayOfLinks, '<a href="https://sheboygan.craigslist.org/">sheboygan</a>');
        array_push($arrayOfLinks, '<a href="https://wausau.craigslist.org/">wausau</a>');
        array_push($arrayOfLinks, '<a href="https://wyoming.craigslist.org/">wyoming</a>');
        array_push($arrayOfLinks, '<a href="https://micronesia.craigslist.org/">guam-micronesia</a>');
        array_push($arrayOfLinks, '<a href="https://puertorico.craigslist.org/">puerto rico</a>');
        array_push($arrayOfLinks, '<a href="https://virgin.craigslist.org/">U.S. virgin islands</a>');
        array_push($arrayOfLinks, '<a href="https://calgary.craigslist.ca/">calgary</a>');
        array_push($arrayOfLinks, '<a href="https://edmonton.craigslist.ca/">edmonton</a>');
        array_push($arrayOfLinks, '<a href="https://ftmcmurray.craigslist.ca/">ft mcmurray</a>');
        array_push($arrayOfLinks, '<a href="https://lethbridge.craigslist.ca/">lethbridge</a>');
        array_push($arrayOfLinks, '<a href="https://hat.craigslist.ca/">medicine hat</a>');
        array_push($arrayOfLinks, '<a href="https://peace.craigslist.ca/">peace river country</a>');
        array_push($arrayOfLinks, '<a href="https://reddeer.craigslist.ca/">red deer</a>');
        array_push($arrayOfLinks, '<a href="https://cariboo.craigslist.ca/">cariboo</a>');
        array_push($arrayOfLinks, '<a href="https://comoxvalley.craigslist.ca/">comox valley</a>');
        array_push($arrayOfLinks, '<a href="https://abbotsford.craigslist.ca/">fraser valley</a>');
        array_push($arrayOfLinks, '<a href="https://kamloops.craigslist.ca/">kamloops</a>');
        array_push($arrayOfLinks, '<a href="https://kelowna.craigslist.ca/">kelowna / okanagan</a>');
        array_push($arrayOfLinks, '<a href="https://kootenays.craigslist.ca/">kootenays</a>');
        array_push($arrayOfLinks, '<a href="https://nanaimo.craigslist.ca/">nanaimo</a>');
        array_push($arrayOfLinks, '<a href="https://princegeorge.craigslist.ca/">prince george</a>');
        array_push($arrayOfLinks, '<a href="https://skeena.craigslist.ca/">skeena-bulkley</a>');
        array_push($arrayOfLinks, '<a href="https://sunshine.craigslist.ca/">sunshine coast</a>');
        array_push($arrayOfLinks, '<a href="https://vancouver.craigslist.ca/">vancouver</a>');
        array_push($arrayOfLinks, '<a href="https://victoria.craigslist.ca/">victoria</a>');
        array_push($arrayOfLinks, '<a href="https://whistler.craigslist.ca/">whistler</a>');
        array_push($arrayOfLinks, '<a href="https://winnipeg.craigslist.ca/">winnipeg</a>');
        array_push($arrayOfLinks, '<a href="https://newbrunswick.craigslist.ca/">new brunswick</a>');
        array_push($arrayOfLinks, '<a href="https://newfoundland.craigslist.ca/">st john\'s</a>');
        array_push($arrayOfLinks, '<a href="https://territories.craigslist.ca/">territories</a>');
        array_push($arrayOfLinks, '<a href="https://yellowknife.craigslist.ca/">yellowknife</a>');
        array_push($arrayOfLinks, '<a href="https://halifax.craigslist.ca/">halifax</a>');
        array_push($arrayOfLinks, '<a href="https://barrie.craigslist.ca/">barrie</a>');
        array_push($arrayOfLinks, '<a href="https://belleville.craigslist.ca/">belleville</a>');
        array_push($arrayOfLinks, '<a href="https://brantford.craigslist.ca/">brantford-woodstock</a>');
        array_push($arrayOfLinks, '<a href="https://chatham.craigslist.ca/">chatham-kent</a>');
        array_push($arrayOfLinks, '<a href="https://cornwall.craigslist.ca/">cornwall</a>');
        array_push($arrayOfLinks, '<a href="https://guelph.craigslist.ca/">guelph</a>');
        array_push($arrayOfLinks, '<a href="https://hamilton.craigslist.ca/">hamilton-burlington</a>');
        array_push($arrayOfLinks, '<a href="https://kingston.craigslist.ca/">kingston</a>');
        array_push($arrayOfLinks, '<a href="https://kitchener.craigslist.ca/">kitchener-waterloo-cambridge</a>');
        array_push($arrayOfLinks, '<a href="https://londonon.craigslist.ca/">london </a>');
        array_push($arrayOfLinks, '<a href="https://niagara.craigslist.ca/">niagara region</a>');
        array_push($arrayOfLinks, '<a href="https://ottawa.craigslist.ca/">ottawa-hull-gatineau</a>');
        array_push($arrayOfLinks, '<a href="https://owensound.craigslist.ca/">owen sound</a>');
        array_push($arrayOfLinks, '<a href="https://peterborough.craigslist.ca/">peterborough</a>');
        array_push($arrayOfLinks, '<a href="https://sarnia.craigslist.ca/">sarnia</a>');
        array_push($arrayOfLinks, '<a href="https://soo.craigslist.ca/">sault ste marie</a>');
        array_push($arrayOfLinks, '<a href="https://sudbury.craigslist.ca/">sudbury</a>');
        array_push($arrayOfLinks, '<a href="https://thunderbay.craigslist.ca/">thunder bay</a>');
        array_push($arrayOfLinks, '<a href="https://toronto.craigslist.ca/">toronto</a>');
        array_push($arrayOfLinks, '<a href="https://windsor.craigslist.ca/">windsor</a>');
        array_push($arrayOfLinks, '<a href="https://pei.craigslist.ca/">prince edward island</a>');
        array_push($arrayOfLinks, '<a href="https://montreal.craigslist.ca/">montreal</a>');
        array_push($arrayOfLinks, '<a href="https://quebec.craigslist.ca/">quebec city</a>');
        array_push($arrayOfLinks, '<a href="https://saguenay.craigslist.ca/">saguenay</a>');
        array_push($arrayOfLinks, '<a href="https://sherbrooke.craigslist.ca/">sherbrooke</a>');
        array_push($arrayOfLinks, '<a href="https://troisrivieres.craigslist.ca/">trois-rivieres</a>');
        array_push($arrayOfLinks, '<a href="https://regina.craigslist.ca/">regina</a>');
        array_push($arrayOfLinks, '<a href="https://saskatoon.craigslist.ca/">saskatoon</a>');
        array_push($arrayOfLinks, '<a href="https://vienna.craigslist.at/">vienna</a>');
        array_push($arrayOfLinks, '<a href="https://brussels.craigslist.org/">belgium</a>');
        array_push($arrayOfLinks, '<a href="https://bulgaria.craigslist.org/">bulgaria</a>');
        array_push($arrayOfLinks, '<a href="https://zagreb.craigslist.org/">croatia</a>');
        array_push($arrayOfLinks, '<a href="https://prague.craigslist.cz/">prague</a>');
        array_push($arrayOfLinks, '<a href="https://copenhagen.craigslist.org/">copenhagen</a>');
        array_push($arrayOfLinks, '<a href="https://helsinki.craigslist.fi/">finland</a>');
        array_push($arrayOfLinks, '<a href="https://bordeaux.craigslist.org/">bordeaux</a>');
        array_push($arrayOfLinks, '<a href="https://rennes.craigslist.org/">brittany</a>');
        array_push($arrayOfLinks, '<a href="https://grenoble.craigslist.org/">grenoble</a>');
        array_push($arrayOfLinks, '<a href="https://lille.craigslist.org/">lille</a>');
        array_push($arrayOfLinks, '<a href="https://loire.craigslist.org/">loire valley</a>');
        array_push($arrayOfLinks, '<a href="https://lyon.craigslist.org/">lyon</a>');
        array_push($arrayOfLinks, '<a href="https://marseilles.craigslist.org/">marseille</a>');
        array_push($arrayOfLinks, '<a href="https://montpellier.craigslist.org/">montpellier</a>');
        array_push($arrayOfLinks, '<a href="https://cotedazur.craigslist.org/">nice / cote d\'azur</a>');
        array_push($arrayOfLinks, '<a href="https://rouen.craigslist.org/">normandy</a>');
        array_push($arrayOfLinks, '<a href="https://paris.craigslist.org/">paris</a>');
        array_push($arrayOfLinks, '<a href="https://strasbourg.craigslist.org/">strasbourg</a>');
        array_push($arrayOfLinks, '<a href="https://toulouse.craigslist.org/">toulouse</a>');
        array_push($arrayOfLinks, '<a href="https://berlin.craigslist.de/">berlin</a>');
        array_push($arrayOfLinks, '<a href="https://bremen.craigslist.de/">bremen</a>');
        array_push($arrayOfLinks, '<a href="https://cologne.craigslist.de/">cologne</a>');
        array_push($arrayOfLinks, '<a href="https://dresden.craigslist.de/">dresden</a>');
        array_push($arrayOfLinks, '<a href="https://dusseldorf.craigslist.de/">dusseldorf</a>');
        array_push($arrayOfLinks, '<a href="https://essen.craigslist.de/">essen / ruhr</a>');
        array_push($arrayOfLinks, '<a href="https://frankfurt.craigslist.de/">frankfurt</a>');
        array_push($arrayOfLinks, '<a href="https://hamburg.craigslist.de/">hamburg</a>');
        array_push($arrayOfLinks, '<a href="https://hannover.craigslist.de/">hannover</a>');
        array_push($arrayOfLinks, '<a href="https://heidelberg.craigslist.de/">heidelberg</a>');
        array_push($arrayOfLinks, '<a href="https://kaiserslautern.craigslist.de/">kaiserslautern</a>');
        array_push($arrayOfLinks, '<a href="https://leipzig.craigslist.de/">leipzig</a>');
        array_push($arrayOfLinks, '<a href="https://munich.craigslist.de/">munich</a>');
        array_push($arrayOfLinks, '<a href="https://nuremberg.craigslist.de/">nuremberg</a>');
        array_push($arrayOfLinks, '<a href="https://stuttgart.craigslist.de/">stuttgart</a>');
        array_push($arrayOfLinks, '<a href="https://athens.craigslist.gr/">greece</a>');
        array_push($arrayOfLinks, '<a href="https://budapest.craigslist.org/">budapest</a>');
        array_push($arrayOfLinks, '<a href="https://reykjavik.craigslist.org/">reykjavik</a>');
        array_push($arrayOfLinks, '<a href="https://dublin.craigslist.org/">dublin</a>');
        array_push($arrayOfLinks, '<a href="https://bologna.craigslist.it/">bologna</a>');
        array_push($arrayOfLinks, '<a href="https://florence.craigslist.it/">florence / tuscany</a>');
        array_push($arrayOfLinks, '<a href="https://genoa.craigslist.it/">genoa</a>');
        array_push($arrayOfLinks, '<a href="https://milan.craigslist.it/">milan</a>');
        array_push($arrayOfLinks, '<a href="https://naples.craigslist.it/">napoli / campania</a>');
        array_push($arrayOfLinks, '<a href="https://perugia.craigslist.it/">perugia</a>');
        array_push($arrayOfLinks, '<a href="https://rome.craigslist.it/">rome</a>');
        array_push($arrayOfLinks, '<a href="https://sardinia.craigslist.it/">sardinia</a>');
        array_push($arrayOfLinks, '<a href="https://sicily.craigslist.it/">sicilia</a>');
        array_push($arrayOfLinks, '<a href="https://torino.craigslist.it/">torino</a>');
        array_push($arrayOfLinks, '<a href="https://venice.craigslist.it/">venice / veneto</a>');
        array_push($arrayOfLinks, '<a href="https://luxembourg.craigslist.org/">luxembourg</a>');
        array_push($arrayOfLinks, '<a href="https://amsterdam.craigslist.org/">amsterdam / randstad</a>');
        array_push($arrayOfLinks, '<a href="https://oslo.craigslist.org/">norway</a>');
        array_push($arrayOfLinks, '<a href="https://warsaw.craigslist.pl/">poland</a>');
        array_push($arrayOfLinks, '<a href="https://faro.craigslist.pt/">faro / algarve</a>');
        array_push($arrayOfLinks, '<a href="https://lisbon.craigslist.pt/">lisbon</a>');
        array_push($arrayOfLinks, '<a href="https://porto.craigslist.pt/">porto</a>');
        array_push($arrayOfLinks, '<a href="https://bucharest.craigslist.org/">romania</a>');
        array_push($arrayOfLinks, '<a href="https://moscow.craigslist.org/">moscow</a>');
        array_push($arrayOfLinks, '<a href="https://stpetersburg.craigslist.org/">st petersburg</a>');
        array_push($arrayOfLinks, '<a href="https://alicante.craigslist.es/">alicante</a>');
        array_push($arrayOfLinks, '<a href="https://baleares.craigslist.es/">baleares</a>');
        array_push($arrayOfLinks, '<a href="https://barcelona.craigslist.es/">barcelona</a>');
        array_push($arrayOfLinks, '<a href="https://bilbao.craigslist.es/">bilbao</a>');
        array_push($arrayOfLinks, '<a href="https://cadiz.craigslist.es/">cadiz</a>');
        array_push($arrayOfLinks, '<a href="https://canarias.craigslist.es/">canarias</a>');
        array_push($arrayOfLinks, '<a href="https://granada.craigslist.es/">granada</a>');
        array_push($arrayOfLinks, '<a href="https://madrid.craigslist.es/">madrid</a>');
        array_push($arrayOfLinks, '<a href="https://malaga.craigslist.es/">malaga</a>');
        array_push($arrayOfLinks, '<a href="https://sevilla.craigslist.es/">sevilla</a>');
        array_push($arrayOfLinks, '<a href="https://valencia.craigslist.es/">valencia</a>');
        array_push($arrayOfLinks, '<a href="https://stockholm.craigslist.se/">sweden</a>');
        array_push($arrayOfLinks, '<a href="https://basel.craigslist.ch/">basel</a>');
        array_push($arrayOfLinks, '<a href="https://bern.craigslist.ch/">bern</a>');
        array_push($arrayOfLinks, '<a href="https://geneva.craigslist.ch/">geneva</a>');
        array_push($arrayOfLinks, '<a href="https://lausanne.craigslist.ch/">lausanne</a>');
        array_push($arrayOfLinks, '<a href="https://zurich.craigslist.ch/">zurich</a>');
        array_push($arrayOfLinks, '<a href="https://istanbul.craigslist.com.tr/">turkey</a>');
        array_push($arrayOfLinks, '<a href="https://ukraine.craigslist.org/">ukraine</a>');
        array_push($arrayOfLinks, '<a href="https://aberdeen.craigslist.co.uk/">aberdeen</a>');
        array_push($arrayOfLinks, '<a href="https://bath.craigslist.co.uk/">bath</a>');
        array_push($arrayOfLinks, '<a href="https://belfast.craigslist.co.uk/">belfast</a>');
        array_push($arrayOfLinks, '<a href="https://birmingham.craigslist.co.uk/">birmingham / west mids</a>');
        array_push($arrayOfLinks, '<a href="https://brighton.craigslist.co.uk/">brighton</a>');
        array_push($arrayOfLinks, '<a href="https://bristol.craigslist.co.uk/">bristol</a>');
        array_push($arrayOfLinks, '<a href="https://cambridge.craigslist.co.uk/">cambridge, UK</a>');
        array_push($arrayOfLinks, '<a href="https://cardiff.craigslist.co.uk/">cardiff / wales</a>');
        array_push($arrayOfLinks, '<a href="https://coventry.craigslist.co.uk/">coventry</a>');
        array_push($arrayOfLinks, '<a href="https://derby.craigslist.co.uk/">derby</a>');
        array_push($arrayOfLinks, '<a href="https://devon.craigslist.co.uk/">devon &amp; cornwall</a>');
        array_push($arrayOfLinks, '<a href="https://dundee.craigslist.co.uk/">dundee</a>');
        array_push($arrayOfLinks, '<a href="https://norwich.craigslist.co.uk/">east anglia</a>');
        array_push($arrayOfLinks, '<a href="https://eastmids.craigslist.co.uk/">east midlands</a>');
        array_push($arrayOfLinks, '<a href="https://edinburgh.craigslist.co.uk/">edinburgh</a>');
        array_push($arrayOfLinks, '<a href="https://essex.craigslist.co.uk/">essex</a>');
        array_push($arrayOfLinks, '<a href="https://glasgow.craigslist.co.uk/">glasgow</a>');
        array_push($arrayOfLinks, '<a href="https://hampshire.craigslist.co.uk/">hampshire</a>');
        array_push($arrayOfLinks, '<a href="https://kent.craigslist.co.uk/">kent</a>');
        array_push($arrayOfLinks, '<a href="https://leeds.craigslist.co.uk/">leeds</a>');
        array_push($arrayOfLinks, '<a href="https://liverpool.craigslist.co.uk/">liverpool</a>');
        array_push($arrayOfLinks, '<a href="https://london.craigslist.co.uk/">london</a>');
        array_push($arrayOfLinks, '<a href="https://manchester.craigslist.co.uk/">manchester</a>');
        array_push($arrayOfLinks, '<a href="https://newcastle.craigslist.co.uk/">newcastle / NE england</a>');
        array_push($arrayOfLinks, '<a href="https://nottingham.craigslist.co.uk/">nottingham</a>');
        array_push($arrayOfLinks, '<a href="https://oxford.craigslist.co.uk/">oxford</a>');
        array_push($arrayOfLinks, '<a href="https://sheffield.craigslist.co.uk/">sheffield</a>');
        array_push($arrayOfLinks, '<a href="https://bangladesh.craigslist.org/">bangladesh</a>');
        array_push($arrayOfLinks, '<a href="https://beijing.craigslist.com.cn/">beijing</a>');
        array_push($arrayOfLinks, '<a href="https://chengdu.craigslist.com.cn/">chengdu</a>');
        array_push($arrayOfLinks, '<a href="https://chongqing.craigslist.com.cn/">chongqing</a>');
        array_push($arrayOfLinks, '<a href="https://dalian.craigslist.com.cn/">dalian</a>');
        array_push($arrayOfLinks, '<a href="https://guangzhou.craigslist.com.cn/">guangzhou</a>');
        array_push($arrayOfLinks, '<a href="https://hangzhou.craigslist.com.cn/">hangzhou</a>');
        array_push($arrayOfLinks, '<a href="https://nanjing.craigslist.com.cn/">nanjing</a>');
        array_push($arrayOfLinks, '<a href="https://shanghai.craigslist.com.cn/">shanghai</a>');
        array_push($arrayOfLinks, '<a href="https://shenyang.craigslist.com.cn/">shenyang</a>');
        array_push($arrayOfLinks, '<a href="https://shenzhen.craigslist.com.cn/">shenzhen</a>');
        array_push($arrayOfLinks, '<a href="https://wuhan.craigslist.com.cn/">wuhan</a>');
        array_push($arrayOfLinks, '<a href="https://xian.craigslist.com.cn/">xi\'an</a>');
        array_push($arrayOfLinks, '<a href="https://micronesia.craigslist.org/">guam-micronesia</a>');
        array_push($arrayOfLinks, '<a href="https://hongkong.craigslist.hk/">hong kong</a>');
        array_push($arrayOfLinks, '<a href="https://ahmedabad.craigslist.co.in/">ahmedabad</a>');
        array_push($arrayOfLinks, '<a href="https://bangalore.craigslist.co.in/">bangalore</a>');
        array_push($arrayOfLinks, '<a href="https://bhubaneswar.craigslist.co.in/">bhubaneswar</a>');
        array_push($arrayOfLinks, '<a href="https://chandigarh.craigslist.co.in/">chandigarh</a>');
        array_push($arrayOfLinks, '<a href="https://chennai.craigslist.co.in/">chennai (madras)</a>');
        array_push($arrayOfLinks, '<a href="https://delhi.craigslist.co.in/">delhi</a>');
        array_push($arrayOfLinks, '<a href="https://goa.craigslist.co.in/">goa</a>');
        array_push($arrayOfLinks, '<a href="https://hyderabad.craigslist.co.in/">hyderabad</a>');
        array_push($arrayOfLinks, '<a href="https://indore.craigslist.co.in/">indore</a>');
        array_push($arrayOfLinks, '<a href="https://jaipur.craigslist.co.in/">jaipur</a>');
        array_push($arrayOfLinks, '<a href="https://kerala.craigslist.co.in/">kerala</a>');
        array_push($arrayOfLinks, '<a href="https://kolkata.craigslist.co.in/">kolkata (calcutta)</a>');
        array_push($arrayOfLinks, '<a href="https://lucknow.craigslist.co.in/">lucknow</a>');
        array_push($arrayOfLinks, '<a href="https://mumbai.craigslist.co.in/">mumbai</a>');
        array_push($arrayOfLinks, '<a href="https://pune.craigslist.co.in/">pune</a>');
        array_push($arrayOfLinks, '<a href="https://surat.craigslist.co.in/">surat surat</a>');
        array_push($arrayOfLinks, '<a href="https://jakarta.craigslist.org/">indonesia</a>');
        array_push($arrayOfLinks, '<a href="https://tehran.craigslist.org/">iran</a>');
        array_push($arrayOfLinks, '<a href="https://baghdad.craigslist.org/">iraq</a>');
        array_push($arrayOfLinks, '<a href="https://haifa.craigslist.org/">haifa</a>');
        array_push($arrayOfLinks, '<a href="https://jerusalem.craigslist.org/">jerusalem</a>');
        array_push($arrayOfLinks, '<a href="https://telaviv.craigslist.org/">tel aviv</a>');
        array_push($arrayOfLinks, '<a href="https://ramallah.craigslist.org/">west bank</a>');
        array_push($arrayOfLinks, '<a href="https://fukuoka.craigslist.jp/">fukuoka</a>');
        array_push($arrayOfLinks, '<a href="https://hiroshima.craigslist.jp/">hiroshima</a>');
        array_push($arrayOfLinks, '<a href="https://nagoya.craigslist.jp/">nagoya</a>');
        array_push($arrayOfLinks, '<a href="https://okinawa.craigslist.jp/">okinawa</a>');
        array_push($arrayOfLinks, '<a href="https://osaka.craigslist.jp/">osaka-kobe-kyoto</a>');
        array_push($arrayOfLinks, '<a href="https://sapporo.craigslist.jp/">sapporo</a>');
        array_push($arrayOfLinks, '<a href="https://sendai.craigslist.jp/">sendai</a>');
        array_push($arrayOfLinks, '<a href="https://tokyo.craigslist.jp/">tokyo</a>');
        array_push($arrayOfLinks, '<a href="https://seoul.craigslist.co.kr/">seoul</a>');
        array_push($arrayOfLinks, '<a href="https://kuwait.craigslist.org/">kuwait</a>');
        array_push($arrayOfLinks, '<a href="https://beirut.craigslist.org/">beirut, lebanon</a>');
        array_push($arrayOfLinks, '<a href="https://malaysia.craigslist.org/">malaysia</a>');
        array_push($arrayOfLinks, '<a href="https://pakistan.craigslist.org/">pakistan</a>');
        array_push($arrayOfLinks, '<a href="https://bacolod.craigslist.com.ph/">bacolod</a>');
        array_push($arrayOfLinks, '<a href="https://naga.craigslist.com.ph/">bicol region</a>');
        array_push($arrayOfLinks, '<a href="https://cdo.craigslist.com.ph/">cagayan de oro</a>');
        array_push($arrayOfLinks, '<a href="https://cebu.craigslist.com.ph/">cebu</a>');
        array_push($arrayOfLinks, '<a href="https://davaocity.craigslist.com.ph/">davao city</a>');
        array_push($arrayOfLinks, '<a href="https://iloilo.craigslist.com.ph/">iloilo</a>');
        array_push($arrayOfLinks, '<a href="https://manila.craigslist.com.ph/">manila</a>');
        array_push($arrayOfLinks, '<a href="https://pampanga.craigslist.com.ph/">pampanga</a>');
        array_push($arrayOfLinks, '<a href="https://zamboanga.craigslist.com.ph/">zamboanga</a>');
        array_push($arrayOfLinks, '<a href="https://singapore.craigslist.com.sg/">singapore</a>');
        array_push($arrayOfLinks, '<a href="https://taipei.craigslist.com.tw/">taiwan</a>');
        array_push($arrayOfLinks, '<a href="https://bangkok.craigslist.co.th/">thailand</a>');
        array_push($arrayOfLinks, '<a href="https://dubai.craigslist.org/">united arab emirates</a>');
        array_push($arrayOfLinks, '<a href="https://vietnam.craigslist.org/">vietnam</a>');
        array_push($arrayOfLinks, '<a href="https://adelaide.craigslist.com.au/">adelaide</a>');
        array_push($arrayOfLinks, '<a href="https://brisbane.craigslist.com.au/">brisbane</a>');
        array_push($arrayOfLinks, '<a href="https://cairns.craigslist.com.au/">cairns</a>');
        array_push($arrayOfLinks, '<a href="https://canberra.craigslist.com.au/">canberra</a>');
        array_push($arrayOfLinks, '<a href="https://darwin.craigslist.com.au/">darwin</a>');
        array_push($arrayOfLinks, '<a href="https://goldcoast.craigslist.com.au/">gold coast</a>');
        array_push($arrayOfLinks, '<a href="https://melbourne.craigslist.com.au/">melbourne</a>');
        array_push($arrayOfLinks, '<a href="https://ntl.craigslist.com.au/">newcastle, NSW</a>');
        array_push($arrayOfLinks, '<a href="https://perth.craigslist.com.au/">perth</a>');
        array_push($arrayOfLinks, '<a href="https://sydney.craigslist.com.au/">sydney</a>');
        array_push($arrayOfLinks, '<a href="https://hobart.craigslist.com.au/">tasmania</a>');
        array_push($arrayOfLinks, '<a href="https://wollongong.craigslist.com.au/">wollongong</a>');
        array_push($arrayOfLinks, '<a href="https://auckland.craigslist.org/">auckland</a>');
        array_push($arrayOfLinks, '<a href="https://christchurch.craigslist.org/">christchurch</a>');
        array_push($arrayOfLinks, '<a href="https://dunedin.craigslist.co.nz/">dunedin</a>');
        array_push($arrayOfLinks, '<a href="https://wellington.craigslist.org/">wellington</a>');
        array_push($arrayOfLinks, '<a href="https://buenosaires.craigslist.org/">buenos aires</a>');
        array_push($arrayOfLinks, '<a href="https://lapaz.craigslist.org/">bolivia</a>');
        array_push($arrayOfLinks, '<a href="https://belohorizonte.craigslist.org/">belo horizonte</a>');
        array_push($arrayOfLinks, '<a href="https://brasilia.craigslist.org/">brasilia</a>');
        array_push($arrayOfLinks, '<a href="https://curitiba.craigslist.org/">curitiba</a>');
        array_push($arrayOfLinks, '<a href="https://fortaleza.craigslist.org/">fortaleza</a>');
        array_push($arrayOfLinks, '<a href="https://portoalegre.craigslist.org/">porto alegre</a>');
        array_push($arrayOfLinks, '<a href="https://recife.craigslist.org/">recife</a>');
        array_push($arrayOfLinks, '<a href="https://rio.craigslist.org/">rio de janeiro</a>');
        array_push($arrayOfLinks, '<a href="https://salvador.craigslist.org/">salvador, bahia</a>');
        array_push($arrayOfLinks, '<a href="https://saopaulo.craigslist.org/">sao paulo</a>');
        array_push($arrayOfLinks, '<a href="https://caribbean.craigslist.org/">caribbean islands</a>');
        array_push($arrayOfLinks, '<a href="https://santiago.craigslist.org/">chile</a>');
        array_push($arrayOfLinks, '<a href="https://colombia.craigslist.org/">colombia</a>');
        array_push($arrayOfLinks, '<a href="https://costarica.craigslist.org/">costa rica</a>');
        array_push($arrayOfLinks, '<a href="https://santodomingo.craigslist.org/">dominican republic</a>');
        array_push($arrayOfLinks, '<a href="https://quito.craigslist.org/">ecuador</a>');
        array_push($arrayOfLinks, '<a href="https://elsalvador.craigslist.org/">el salvador</a>');
        array_push($arrayOfLinks, '<a href="https://guatemala.craigslist.org/">guatemala</a>');
        array_push($arrayOfLinks, '<a href="https://acapulco.craigslist.com.mx/">acapulco</a>');
        array_push($arrayOfLinks, '<a href="https://bajasur.craigslist.com.mx/">baja california sur</a>');
        array_push($arrayOfLinks, '<a href="https://chihuahua.craigslist.com.mx/">chihuahua</a>');
        array_push($arrayOfLinks, '<a href="https://juarez.craigslist.com.mx/">ciudad juarez</a>');
        array_push($arrayOfLinks, '<a href="https://guadalajara.craigslist.com.mx/">guadalajara</a>');
        array_push($arrayOfLinks, '<a href="https://guanajuato.craigslist.com.mx/">guanajuato</a>');
        array_push($arrayOfLinks, '<a href="https://hermosillo.craigslist.com.mx/">hermosillo</a>');
        array_push($arrayOfLinks, '<a href="https://mazatlan.craigslist.com.mx/">mazatlan</a>');
        array_push($arrayOfLinks, '<a href="https://mexicocity.craigslist.com.mx/">mexico city</a>');
        array_push($arrayOfLinks, '<a href="https://monterrey.craigslist.com.mx/">monterrey</a>');
        array_push($arrayOfLinks, '<a href="https://oaxaca.craigslist.com.mx/">oaxaca</a>');
        array_push($arrayOfLinks, '<a href="https://puebla.craigslist.com.mx/">puebla</a>');
        array_push($arrayOfLinks, '<a href="https://pv.craigslist.com.mx/">puerto vallarta</a>');
        array_push($arrayOfLinks, '<a href="https://tijuana.craigslist.com.mx/">tijuana</a>');
        array_push($arrayOfLinks, '<a href="https://veracruz.craigslist.com.mx/">veracruz</a>');
        array_push($arrayOfLinks, '<a href="https://yucatan.craigslist.com.mx/">yucatan</a>');
        array_push($arrayOfLinks, '<a href="https://managua.craigslist.org/">nicaragua</a>');
        array_push($arrayOfLinks, '<a href="https://panama.craigslist.org/">panama</a>');
        array_push($arrayOfLinks, '<a href="https://lima.craigslist.org/">peru</a>');
        array_push($arrayOfLinks, '<a href="https://puertorico.craigslist.org/">puerto rico</a>');
        array_push($arrayOfLinks, '<a href="https://montevideo.craigslist.org/">montevideo</a>');
        array_push($arrayOfLinks, '<a href="https://caracas.craigslist.org/">venezuela</a>');
        array_push($arrayOfLinks, '<a href="https://virgin.craigslist.org/">virgin islands</a>');
        array_push($arrayOfLinks, '<a href="https://cairo.craigslist.org/">egypt</a>');
        array_push($arrayOfLinks, '<a href="https://addisababa.craigslist.org/">ethiopia</a>');
        array_push($arrayOfLinks, '<a href="https://accra.craigslist.org/">ghana</a>');
        array_push($arrayOfLinks, '<a href="https://kenya.craigslist.org/">kenya</a>');
        array_push($arrayOfLinks, '<a href="https://casablanca.craigslist.org/">morocco</a>');
        array_push($arrayOfLinks, '<a href="https://capetown.craigslist.co.za/">cape town</a>');
        array_push($arrayOfLinks, '<a href="https://durban.craigslist.co.za/">durban</a>');
        array_push($arrayOfLinks, '<a href="https://johannesburg.craigslist.co.za/">johannesburg</a>');
        array_push($arrayOfLinks, '<a href="https://pretoria.craigslist.co.za/">pretoria</a>');
        array_push($arrayOfLinks, '<a href="https://tunis.craigslist.org/">tunisia</a>');
        $this->arrayOfLinks = $arrayOfLinks;
    }

}

